### ISSUE TITLE
High vulnerability, update axios from 0.19.2 to 0.21.1

### ISSUE THREAD

**Issue by aikozijlemans** [MeatReed/amethyse-api#10]
High            Server-Side Request Forgery                                   
                                                                                
  Package         axios                                                         
                                                                                
  Patched in      >=0.21.1                                                      
                                                                                
  Dependency of   amethyste-api                                                 
                                                                                
  Path            amethyste-api > axios                                         
                                                                                
  More info       https://npmjs.com/advisories/1594

**Comment by jorisdugue** [comment]
> High Server-Side Request Forgery
> 
> Package axios
> 
> Patched in >=0.21.1
> 
> Dependency of amethyste-api
> 
> Path amethyste-api > axios
> 
> More info https://npmjs.com/advisories/1594

Fixed here => https://github.com/MeatReed/amethyste-api/commit/ae259f10016b4af7ad9bf0d812ad229ebc2d0436 
Thx for report the vulnerability 😄
